### ISSUE TITLE
IndexedEnumerableSetLib

### ISSUE THREAD

**Issue by OR13** [transmute-industries/transmute-framework#19]
I have removed this library from this branch:

https://github.com/transmute-industries/transmute-framework/tree/sol

I have a number of concerns regarding using it, which we should chat about in person.

My main concerns are that the interface seems to change (address to bytes32), the tests do not always pass or exist for both versions...

Its basically really hard to use.

I do see it as valuable, especially for implementing security rules inside contracts. 

It needs test coverage and better documentation to be included.

I'm happy to take point a rewrite of it, but right now, its getting in my way, so I'm removing it.

**Comment by eolszewski** [comment]
Okay.

**Comment by OR13** [comment]
It seems that these sets are type specific, so there really needs to be 3 implementations:

TransmuteUIntSet
TransmuteBytes32Set
TransmuteAddressSet

**Comment by eolszewski** [comment]
What does this library get us in the EventStore? Why are you reopening this if you're telling me you're going to delete it?

**Comment by OR13** [comment]
I want it fixed. There are security problems which this library can solve for us.
In the Faucet, this library is used for authorization. It seems useful for that, I'd like to use it to add authorization to EventStores, so that read model can be used to build state, but the set library will ensure read and write access is enforced by contract.

**Comment by OR13** [comment]
I will take point on rewriting

**Comment by eolszewski** [comment]
I don't see this as being a rewrite. I just see it as duplicating it three times over with different types.

**Comment by OR13** [comment]
I got this to build and pushed to this branch, it would be awesome to get our tests in order for this.
