### ISSUE TITLE
Add sender address as default field on events.

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-framework#29]
Per http://danielwhittaker.me/2014/10/18/6-code-smells-cqrs-events-avoid/

This field is commonly required in line of business applications and can be used to build audit logs. It is a common field, but not always necessary and depends on the specific domain.

**Comment by OR13** [comment]
This is done, its called TxOrigin, and it lives on meta object of transmute events.

https://transmute-framework.firebaseapp.com/interfaces/_eventstore_eventtypes_eventtypes_.eventtypes.itransmuteeventmeta.html#txorigin

closing.
