### ISSUE TITLE
Add version field to events

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-framework#30]
Version – The version number allows the developer to handle concurrency conflicts and partial connection scenarios. For more information, take a look at Handling Concurrency Issues in a CQRS Event Sourced system.

This is for down the line - could be useful for projections and handling older event types accordingly.

**Comment by eolszewski** [comment]
http://danielwhittaker.me/2015/02/02/upgrade-cqrs-events-without-busting/

**Comment by OR13** [comment]
This has been implemented

file:///Users/orie/TransmuteIndustries/transmute-framework/docs/interfaces/_eventstore_eventtypes_eventtypes_.eventtypes.itransmuteeventmeta.html#version
