### ISSUE TITLE
Refactor EventStore and Middleware to Classes

### ISSUE THREAD

**Issue by OR13** [transmute-industries/transmute-framework#52]
With the addition of Offchain events like ipfs, we now have need for storing different kinds of objects.

- SolidityStruct persisted objects where EsEvent.ValueType === 'Object'
- IpfsObjects EsEvent.ValueType === 'String', and StringValue === 'ipfs/....'

This means that middleware needs to be aware of user preferences for how objects are stored.

currently the framework is initialized like so:

```
TransmuteFramework.init({
                env: 'infura',
                esa: eventStoreArtifacts,
                esfa: eventStoreFactoryArtifacts
            })

TransmuteFramework.TransmuteIpfs.init({
                host: 'localhost',
                port: '5001',
                options: {
                    protocol: 'http'
                }
            })
```

This is problematic. Not all framework consumers will want IPFS.
When reading and writing objects, the objects should contain all information necessary to know where they are stored.

however, when writing a command, that is an object. currently the framework must be set to store objects on IPFS or on chain, but not both.

For the time being I'm assuming objects want to be stored in ipfs.

These configuration concerns need to be addressed, there should be a single init call which defines how the framework will be used. Middleware and whatever else need to be aware of that state.

This means that TypeScript modules need to be replaced with classes.

**Comment by OR13** [comment]
Here's how this should work:

```
TransmuteFramework.init({
    env: 'infura',
    esa: eventStoreArtifacts,
    esfa: eventStoreFactoryArtifacts,
    ipfsConfig: {
        host: 'localhost',
        port: '5001',
        options: {
            protocol: 'http'
        }
    }
})
```

When writing a command: 

```
{
    type: 'IPFS:RECORD:CREATED',
    payload: {
        cool: 'story...bro'
    },
    meta: {
        handlers: ['ipfs']
    }
}
```

the meta.handlers is used to determine where the offchain data will be stored.
the config at the top level is used to determine how that data will be stored.

**Comment by eolszewski** [comment]
This is reasonable, we are going to need to end up providing an additional example for offchain data storage so that people can see how to easily set up something more familiar like Postgresql config in our init function. 

I agree with storing the handlers in meta - I think we are going to want to integrate another familiar backend like what I mentioned to be able to show the utilization of multiple handlers in the framework. But I think this is something post pre-alpha.

**Comment by OR13** [comment]
This is done
